services:
  goblin-api:
    build:
      context: ./goblin-api
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Changed to Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
    volumes: 
      - ./goblin-api:/app

  goblin-webapp: 
    build:
      context: ./goblin-webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes: # Re-enabled for development
      - ./goblin-webapp:/app 
      - /app/node_modules 
    environment: # Re-enabled CHOKIDAR_USEPOLLING for development
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - goblin-api 

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goblindb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
