services:
  goblin-api:
    build:
      context: ./goblin-api
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
    volumes:
      - ./goblin-api:/app

  goblin-webapp: # Add this new service for the React frontend
    build:
      context: ./goblin-webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose React app on port 3000
    volumes:
      - ./goblin-webapp:/app # Mount the local frontend code for development
      - /app/node_modules # Don't mount local node_modules, use the ones in the container
    environment:
      - CHOKIDAR_USEPOLLING=true # Useful for Docker volume mounting and hot reloading
    depends_on:
      - goblin-api # Optional: if frontend needs API to be up first

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goblindb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
